name: Schema Migrator

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/schema-migrator.yaml"
      - "components/schema-migrator/**"
      - "scripts/**"
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/schema-migrator.yaml"
      - "components/schema-migrator/**"
      - "scripts/**"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up go environment
      uses: actions/setup-go@v5
      with:
        go-version-file: components/schema-migrator/go.mod
        cache-dependency-path: components/schema-migrator/go.sum
    - name: Run tests
      run: make -C components/schema-migrator release

  build:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: control-plane/schema-migrator
      dockerfile: Dockerfile
      context: components/schema-migrator
